// Generated by CoffeeScript 1.3.3
(function() {

  angular.module('lankar', [], function($compileProvider, $routeProvider) {
    $compileProvider.directive('compile', function($compile) {
      var converter;
      converter = new Markdown.Converter();
      return function(scope, element, attrs) {
        return scope.$watch(function(scope) {
          return converter.makeHtml(scope.$eval(attrs.compile));
        }, function(value) {
          element.html(value);
          return $compile(element.contents())(scope);
        });
      };
    });
    return $routeProvider.when('/links/:page', {
      templateUrl: 'partials/links.html',
      controller: this.LinksCtrl
    }).when('/add', {
      templateUrl: 'partials/form.html'
    }).otherwise({
      redirectTo: '/links/1'
    });
  });

  this.LinksCtrl = function($scope, $http, $routeParams) {
    return $http.get('index.php/dblinks/' + $routeParams.page).success(function(data) {
      $scope.links = data.links;
      $scope.total = parseInt(data.total);
      $scope.page = parseInt($routeParams.page);
      $scope.isfirst = $scope.page === 1;
      return $scope.islast = $scope.page === $scope.total;
    });
  };

}).call(this);
